server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_wfx?characterEncoding=UTF-8
      username: root
      password: 666666
  redis:
    host: 192.168.79.135
    port: 6379
    password: Redis@bess777
    jedis:
      pool:
        min-idle: 30
        max-wait: 1000
        max-active: 8
    database: 0
    timeout: 100
redisson:
  addr:
    singleAddr:
      host: redis://192.168.79.135:6379
      password: Redis@bess777
      database: 0

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.bess.springboot.wfx.pojo
logging:
  file:
    max-size: 10MB
    path: log
